<?php

namespace Database\Seeders;

use App\Enums\ProductStatus;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductDemoSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Categories
        $categories = [
            'Hydraulics' => Category::firstOrCreate(['name' => 'Hydraulics'], [
                'prefix'         => 'HYD',
                'chinese_name'   => '液压件',
                'allow_variants' => 0,
            ]),
            'Engine Parts' => Category::firstOrCreate(['name' => 'Engine Parts'], [
                'prefix'         => 'ENG',
                'chinese_name'   => '发动机件',
                'allow_variants' => 0,
            ]),
            'Undercarriage' => Category::firstOrCreate(['name' => 'Undercarriage'], [
                'prefix'         => 'UND',
                'chinese_name'   => '底盘件',
                'allow_variants' => 0,
            ]),
            'Electrical & Sensors' => Category::firstOrCreate(['name' => 'Electrical & Sensors'], [
                'prefix'         => 'ELE',
                'chinese_name'   => '电器传感器',
                'allow_variants' => 0,
            ]),
            'Filters & Maintenance' => Category::firstOrCreate(['name' => 'Filters & Maintenance'], [
                'prefix'         => 'FLT',
                'chinese_name'   => '滤芯保养件',
                'allow_variants' => 0,
            ]),
        ];

        // 2. Realistic ZTG Heavy Parts Products
        $products = [
            // Filters
            [
                'name'         => 'Engine Oil Filter 1R-0716',
                'chinese_name' => '机油滤芯',
                'part_no'      => '1R-0716',
                'category_id'  => $categories['Filters & Maintenance']->id,
                'uom'          => 'pcs',
                'address'      => 'A-01-01',
                'stock'        => 50,
                'alert_limit'  => 10,
                'price1'       => 850.00,
                'price2'       => 780.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'Heavy duty oil filter for CAT C9/C13 series.',
            ],
            [
                'name'         => 'Fuel Water Separator 326-1644',
                'chinese_name' => '油水分离滤芯',
                'part_no'      => '326-1644',
                'category_id'  => $categories['Filters & Maintenance']->id,
                'uom'          => 'pcs',
                'address'      => 'A-01-02',
                'stock'        => 40,
                'alert_limit'  => 8,
                'price1'       => 1450.00,
                'price2'       => 1350.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'High efficiency fuel water separator.',
            ],
            [
                'name'         => 'Primary Air Filter Element 6I-2505',
                'chinese_name' => '空气滤芯主芯',
                'part_no'      => '6I-2505',
                'category_id'  => $categories['Filters & Maintenance']->id,
                'uom'          => 'pcs',
                'address'      => 'A-02-01',
                'stock'        => 25,
                'alert_limit'  => 5,
                'price1'       => 2200.00,
                'price2'       => 2050.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'Radial seal primary air filter.',
            ],

            // Hydraulics
            [
                'name'         => 'Hydraulic Main Pump Assembly K3V112DT',
                'chinese_name' => '主液压泵总成',
                'part_no'      => 'K3V112DT',
                'category_id'  => $categories['Hydraulics']->id,
                'uom'          => 'unit',
                'address'      => 'B-01-01',
                'stock'        => 6,
                'alert_limit'  => 2,
                'price1'       => 68000.00,
                'price2'       => 64000.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'Kawasaki K3V series main pump for 20-ton excavators.',
            ],
            [
                'name'         => 'Boom Cylinder Seal Kit SKF-320D',
                'chinese_name' => '动臂油缸修理包',
                'part_no'      => 'SKF-320D',
                'category_id'  => $categories['Hydraulics']->id,
                'uom'          => 'kit',
                'address'      => 'B-02-03',
                'stock'        => 30,
                'alert_limit'  => 5,
                'price1'       => 3500.00,
                'price2'       => 3200.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'NOK high-temperature hydraulic cylinder seal kit.',
            ],
            [
                'name'         => 'Pilot Relief Valve Assembly 708-2L-00300',
                'chinese_name' => '先导溢流阀总成',
                'part_no'      => '708-2L-00300',
                'category_id'  => $categories['Hydraulics']->id,
                'uom'          => 'pcs',
                'address'      => 'B-03-02',
                'stock'        => 15,
                'alert_limit'  => 3,
                'price1'       => 8500.00,
                'price2'       => 7900.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'High precision hydraulic pilot relief valve.',
            ],

            // Engine Parts
            [
                'name'         => 'Turbocharger TD04HL-15T',
                'chinese_name' => '涡轮增压器',
                'part_no'      => '49189-00501',
                'category_id'  => $categories['Engine Parts']->id,
                'uom'          => 'unit',
                'address'      => 'C-01-01',
                'stock'        => 12,
                'alert_limit'  => 2,
                'price1'       => 18500.00,
                'price2'       => 17200.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'Mitsubishi water-cooled turbocharger unit.',
            ],
            [
                'name'         => 'Common Rail Fuel Injector 0445120236',
                'chinese_name' => '共轨燃油喷油嘴',
                'part_no'      => '0445120236',
                'category_id'  => $categories['Engine Parts']->id,
                'uom'          => 'pcs',
                'address'      => 'C-01-04',
                'stock'        => 24,
                'alert_limit'  => 6,
                'price1'       => 9800.00,
                'price2'       => 9200.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'Bosch genuine common rail injector for 6D107 engine.',
            ],
            [
                'name'         => 'Piston Ring Set 6D16 Std',
                'chinese_name' => '活塞环标准件',
                'part_no'      => 'ME999981',
                'category_id'  => $categories['Engine Parts']->id,
                'uom'          => 'set',
                'address'      => 'C-02-02',
                'stock'        => 18,
                'alert_limit'  => 4,
                'price1'       => 4200.00,
                'price2'       => 3800.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'Complete 6-cylinder standard size piston ring set.',
            ],
            [
                'name'         => 'Water Pump Assembly 6D34',
                'chinese_name' => '发动机水泵总成',
                'part_no'      => 'ME993520',
                'category_id'  => $categories['Engine Parts']->id,
                'uom'          => 'unit',
                'address'      => 'C-03-01',
                'stock'        => 14,
                'alert_limit'  => 3,
                'price1'       => 5600.00,
                'price2'       => 5200.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'Cooling system engine water pump with gasket.',
            ],

            // Undercarriage
            [
                'name'         => 'Track Roller Bottom 320D',
                'chinese_name' => '支重轮',
                'part_no'      => '118-1614',
                'category_id'  => $categories['Undercarriage']->id,
                'uom'          => 'pcs',
                'address'      => 'D-01-01',
                'stock'        => 32,
                'alert_limit'  => 6,
                'price1'       => 3200.00,
                'price2'       => 2950.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'Single flange heavy-duty bottom track roller.',
            ],
            [
                'name'         => 'Excavator Bucket Tooth 1U3352',
                'chinese_name' => '挖斗斗齿',
                'part_no'      => '1U3352',
                'category_id'  => $categories['Undercarriage']->id,
                'uom'          => 'pcs',
                'address'      => 'D-02-01',
                'stock'        => 120,
                'alert_limit'  => 20,
                'price1'       => 650.00,
                'price2'       => 580.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'Standard long bucket tooth J350 series with pin & retainer.',
            ],
            [
                'name'         => 'Front Idler Wheel Assembly PC200-8',
                'chinese_name' => '导向轮总成',
                'part_no'      => '20Y-30-00011',
                'category_id'  => $categories['Undercarriage']->id,
                'uom'          => 'unit',
                'address'      => 'D-03-01',
                'stock'        => 8,
                'alert_limit'  => 2,
                'price1'       => 16500.00,
                'price2'       => 15500.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'Forged steel front idler group with heavy seal.',
            ],

            // Electrical & Sensors
            [
                'name'         => 'Starter Motor 24V 7.5KW M8T80071',
                'chinese_name' => '起动机马达 24V',
                'part_no'      => 'M8T80071',
                'category_id'  => $categories['Electrical & Sensors']->id,
                'uom'          => 'unit',
                'address'      => 'E-01-01',
                'stock'        => 10,
                'alert_limit'  => 2,
                'price1'       => 14500.00,
                'price2'       => 13800.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'Heavy duty 24V 11-teeth gear starter motor.',
            ],
            [
                'name'         => 'Main Hydraulic Pressure Sensor 7861-93-1651',
                'chinese_name' => '主压力传感器',
                'part_no'      => '7861-93-1651',
                'category_id'  => $categories['Electrical & Sensors']->id,
                'uom'          => 'pcs',
                'address'      => 'E-01-03',
                'stock'        => 22,
                'alert_limit'  => 4,
                'price1'       => 2800.00,
                'price2'       => 2550.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => '50Mpa high pressure sensor switch.',
            ],
            [
                'name'         => 'Proportional Solenoid Valve KDRDE5K-31/30C50',
                'chinese_name' => '比例电磁阀',
                'part_no'      => 'KDRDE5K-31',
                'category_id'  => $categories['Electrical & Sensors']->id,
                'uom'          => 'pcs',
                'address'      => 'E-02-02',
                'stock'        => 16,
                'alert_limit'  => 3,
                'price1'       => 3600.00,
                'price2'       => 3300.00,
                'status'       => ProductStatus::ACTIVE,
                'is_dead_stock'=> false,
                'damaged'      => 0,
                'notes'        => 'Hydraulic pump regulator proportional solenoid valve.',
            ],
        ];

        foreach ($products as $p) {
            Product::firstOrCreate(['part_no' => $p['part_no']], $p);
        }
    }
}
